In [16]:
# Instalamos el paquete para descargar archivos como indica la clase
!pip install wget

from wget import download
from os import path

url_txt = "https://ignaciorlando.github.io/datasets/data-science/ObesityDataSet_raw_and_data_sinthetic.txt"
url_csv = "https://ignaciorlando.github.io/datasets/data-science/ObesityDataSet_raw_and_data_sinthetic.csv"

# Descargamos los archivos chequeando primero si ya existen
if not path.exists("ObesityDataSet_raw_and_data_sinthetic.txt"):
    download(url_txt)
else:
    print("El archivo de descripción ya existe.")

if not path.exists("ObesityDataSet_raw_and_data_sinthetic.csv"):
    download(url_csv)
else:
    print("El archivo de datos ya existe.")

Requirement already satisfied: wget in ./env/lib/python3.12/site-packages (3.2)
El archivo de descripción ya existe.
El archivo de datos ya existe.

In [7]:
#Leer el archivo de descripcion
#with para que el archivo se cierre solo al terminar
with open("ObesityDataSet_raw_and_data_sinthetic.txt", "r") as f:
    descripcion = f.read()
    print(descripcion)

Obesidad

La obesidad, que causa problemas físicos y mentales, es un problema de salud global con graves consecuencias. La prevalencia de la obesidad aumenta constantemente, por lo que se necesita nueva investigación que examine los factores que influyen en la obesidad y cómo predecir la aparición de la condición según estos factores.

Los datos fueron recolectados como parte de este trabajo científico: https://www.sciencedirect.com/science/article/pii/S2352340919306985#sec1

Información del Conjunto de Datos

Este conjunto de datos incluye información para la estimación de los niveles de obesidad en individuos de los países de México, Perú y Colombia, en función de sus hábitos alimenticios y condición física. Los datos contienen 17 atributos y 2111 registros, los registros están etiquetados con la variable de clase NObesidad (Nivel de Obesidad), que permite la clasificación de los datos utilizando los valores de Peso Insuficiente, Peso Normal, Sobrepeso Nivel I, Sobrepeso Nivel II, Obesidad Tipo I, Obesidad Tipo II y Obesidad Tipo III. El 77% de los datos se generó sintéticamente utilizando la herramienta Weka y el filtro SMOTE, el 23% de los datos se recolectaron directamente de los usuarios a través de una plataforma web.

Las columnas corresponden a:

Age: age

Height: height

Weight: weight

family_history_with_overweight: Has a family member suffered or suffers f from overweight? - yes or no

FAVC: Frequent consumption of high caloric food - yes or no

FCVC: Frequency of consumption of vegetables - Never, Sometimes, Always

NCP: Number of main meals - 1, 2, 3, 4

CAEC: Consumption of food between meals - No, Sometimes, Frequently, Always

SMOKE: Do you smoke - yes o no

CH2O: Consumption of water daily - Less than a litter, between 1 and 2 l, more than 2 l

SCC: Calories consumption monitoring - yes or no

FAF: Physical activity frequency - 0, 1 to 2, 2 to 4, 4 to 5

TUE: Time using technology devices - 0 to 2, 3 to 5, >5

CALC: Consumption of alcohol - no, sometimes, frequently, always

MTRANS: Transportation used - automobile, motorbike, bike, public_transportation, walking

NObeyesdad: Type of obesity - insufficient_weight, normal_weight, overweight-level_i, overweight-level_ii, obesity_type_i, obesity_type_ii, obesity_type_iii
BMI: Body mass index

In [10]:
#Leer el archivo de datos
import pandas as pd

df_obesidad = pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.csv")
df_obesidad.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [11]:
df_obesidad.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

Age: Cuantitativa continua. Representa la edad (tiene decimales porque los datos fueron generados sintéticamente).

Height: Cuantitativa continua. Es la altura de la persona en metros.

Weight: Cuantitativa continua. Es el peso en kilos.

family_history_with_overweight: Cualitativa nominal (binaria). Indica si la persona tiene familiares con sobrepeso (sí o no).

FAVC: Cualitativa nominal (binaria). Consumo frecuente de comida alta en calorías (sí o no).

FCVC: Cualitativa ordinal. Frecuencia con la que come vegetales (nunca, a veces, siempre).

NCP: Cuantitativa discreta. Cantidad de comidas principales al día (1, 2, 3 o 4).

CAEC: Cualitativa ordinal. Frecuencia con la que come entre comidas (no, a veces, frecuentemente, siempre).

SMOKE: Cualitativa nominal (binaria). Indica si la persona fuma (sí o no).

CH2O: Cualitativa ordinal. Cantidad de agua que toma al día (menos de 1 litro, entre 1 y 2, o más de 2).

SCC: Cualitativa nominal (binaria). Si monitorea las calorías que consume (sí o no).

FAF: Cualitativa ordinal. Frecuencia de actividad física expresada en rangos de días (0, 1 a 2, 2 a 4, etc.).

TUE: Cualitativa ordinal. Tiempo de uso de dispositivos tecnológicos en rangos de horas (0 a 2, 3 a 5, >5).

CALC: Cualitativa ordinal. Frecuencia de consumo de alcohol (no, a veces, frecuentemente, siempre).

MTRANS: Cualitativa nominal. El medio de transporte que usa (auto, moto, bondi, bici o caminando). No hay un orden de jerarquía lógico entre ellos.

NObeyesdad: Cualitativa ordinal. Es el diagnóstico o nivel de obesidad (desde bajo peso hasta obesidad tipo III). Tiene un orden claro de gravedad.

BMI: Cuantitativa continua. Es el Índice de Masa Corporal (resultado de un cálculo matemático exacto).

In [15]:
from wget import download
from os import path

url_netflix_txt = "https://ignaciorlando.github.io/datasets/data-science/netflix_titles.txt"
url_netflix_csv = "https://ignaciorlando.github.io/datasets/data-science/netflix_titles.csv"

if not path.exists("netflix_titles.txt"):
    download(url_netflix_txt)
else:
    print("El archivo de descripción ya existe.")

if not path.exists("netflix_titles.csv"):
    download(url_netflix_csv)
else:
    print("El archivo de datos ya existe.")

El archivo de descripción ya existe.
El archivo de datos ya existe.

In [17]:
with open("netflix_titles.txt", "r", encoding="utf-8") as f:
    descripcion_netflix = f.read()
    print(descripcion_netflix)

Películas y Series de TV de Netflix

Acerca del Conjunto de Datos

Netflix es una fuerza líder en el ámbito de los medios y la transmisión de video. Con una asombrosa variedad de más de 8,000 películas y programas de televisión accesibles en su plataforma, a mediados de 2021, su cantidad de suscriptores globales superaba los 200 millones. Este conjunto de datos tabulado cataloga exhaustivamente todas las ofertas en Netflix, incluidos detalles vitales como elenco, directores, calificaciones, año de lanzamiento, duración y más.

Descripción General del Conjunto de Datos:

El conjunto de datos de Títulos de Netflix es una compilación completa de películas y programas de televisión disponibles en Netflix, que cubre diversos aspectos como el tipo de título, director, elenco, país de producción, año de lanzamiento, calificación, duración, géneros (listados) y una breve descripción. Este conjunto de datos es fundamental para analizar tendencias en el contenido de Netflix, comprender la popularidad de los géneros y examinar la distribución del contenido en diferentes regiones y períodos de tiempo.

Si abriéramos este archivo manualmente en Excel o lo miráramos crudo, notaríamos un par de cosas peligrosas para Python:

Separadores engañosos: Hay columnas (como la descripción o el elenco) que contienen textos largos llenos de comas. Si Python cortara a ciegas por cada coma, rompería la tabla entera. Pandas soluciona esto respetando las comillas dobles (") que envuelven esos textos.

Caracteres especiales (Encoding): Al ser un catálogo internacional, hay nombres con tildes y símbolos raros. Si lo abrimos con la codificación por defecto, Python podría tirar un UnicodeDecodeError. Vamos a tener que forzar la lectura pasándole un parámetro de encoding (como latin-1).

Columnas fantasma: Cada fila tiene un montón de comas vacías al final. Pandas va a leer esto y nos va a crear columnas inútiles llenas de valores nulos (NaN) llamadas Unnamed.

Tipos de datos mezclados: La columna de duración dice "90 min" o "2 Seasons". Al incluir letras, Pandas no la va a tratar como un número matemático, sino como un texto (string).

In [18]:
import pandas as pd

df_netflix = pd.read_csv("netflix_titles.csv", encoding="latin-1")

print("Las columnas del dataset son:")
print(df_netflix.columns.tolist())

df_netflix.head()

Las columnas del dataset son:
['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_netflix.describe()

,release_year,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
count,8809.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2014.181292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,8.818932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1925.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Si, faltan muchas columnas haciendo describe().! Al ver el resultado, notamos que la única columna original que aparece es release_year (año de lanzamiento), acompañada por un montón de columnas vacías generadas por error (Unnamed: 12, Unnamed: 13, etc.). No están los títulos, ni los directores, ni el país.
Esto ocurre porque el método describe() de Pandas, por defecto, solo calcula estadísticas sobre variables cuantitativas (numéricas). Todas las demás columnas del dataset son detectadas como variables cualitativas (texto), y Pandas las excluye automáticamente porque es imposible calcularle un "promedio" o un "máximo" matemático a un bloque de texto.

show_id: Cualitativa nominal. Es simplemente un identificador alfanumérico único para cada obra.

type: Cualitativa nominal (binaria). Indica la categoría del contenido, con solo dos opciones: "Movie" o "TV Show".

title: Cualitativa nominal. Texto que representa el nombre de la película o serie.

director, cast (elenco), country (país): Cualitativas nominales. Son variables de texto sin un orden jerárquico. (Ojo: a veces incluyen varios valores separados por comas).

date_added: Cuantitativa (formato fecha) o Cualitativa Ordinal (si la pensamos como una cronología temporal). Indica cuándo se subió a la plataforma.

release_year: Cuantitativa discreta. Año original en que se estrenó la obra (número entero sin decimales).  

rating: Cualitativa ordinal. Es la clasificación por edades (TV-Y, PG-13, TV-MA). Existe una relación de orden lógico desde apto para todo público hasta contenido para adultos.  

duration: Cuantitativa discreta (representa minutos o temporadas), pero como está mezclada con texto ("90 min", "2 Seasons"), Pandas la detecta temporalmente como Cualitativa nominal (texto).

listed_in: Cualitativa nominal. Los géneros de la obra.

description: Cualitativa nominal (texto no estructurado).

Columnas Unnamed (12 a 25): Son columnas basura llenas de valores nulos (NaN), generadas automáticamente porque Pandas leyó comas accidentales al final de las filas.

In [21]:
#i)Cuantos direactores distintos hay
cantidad_directores = df_netflix['director'].nunique()
print(f"i)Hay {cantidad_directores} directores distintos registrados")

i)Hay 4529 directores distintos registrados

In [22]:
#ii)Quien es el director con mas peliculas
solo_peliculas = df_netflix[df_netflix['type'] == 'Movie']
director_top = solo_peliculas['director'].value_counts().index[0]
cantidad_top = solo_peliculas['director'].value_counts().iloc[0]
print(f"ii) El director con más películas es {director_top} (con {cantidad_top} películas).")

ii) El director con más películas es Rajiv Chilaka (con 19 películas).

In [23]:
#iii)Cuantas series hay?y cuantos programas de tv?
conteo_tipos = df_netflix['type'].value_counts()
print(f"iii) En la base de datos hay:\n{conteo_tipos}")

iii) En la base de datos hay:
type
Movie      6132
TV Show    2677
Name: count, dtype: int64

In [25]:
#iv)Cual es la peli mas vieja del catalogo?y la serie?
peli_mas_vieja = solo_peliculas.sort_values(by='release_year').iloc[0]
solo_series = df_netflix[df_netflix['type'] == 'TV Show']
serie_mas_vieja = solo_series.sort_values(by='release_year').iloc[0]

print(f"iv) Película más vieja: '{peli_mas_vieja['title']}' (del año {peli_mas_vieja['release_year']})")
print(f"iv) Serie más vieja: '{serie_mas_vieja['title']}' (del año {serie_mas_vieja['release_year']})")

iv) Película más vieja: 'Prelude to War' (del año 1942)
iv) Serie más vieja: 'Pioneers: First Women Filmmakers*' (del año 1925)

In [26]:
#v)Dado un pais, determinar cuantas peliculas de ese pais hay
pais_elegido = "Argentina"
pelis_del_pais = solo_peliculas[solo_peliculas['country'].fillna('').str.contains(pais_elegido)]
cantidad_pais = len(pelis_del_pais)
print(f"v) Hay {cantidad_pais} películas producidas (o co-producidas) en {pais_elegido}.")

v) Hay 71 películas producidas (o co-producidas) en Argentina.

In [29]:
!pip install openpyxl
# i) Descargar automáticamente el archivo
from wget import download
from os import path

url_streaming = "https://ignaciorlando.github.io/datasets/data-science/catalogo_streaming_argentina_2024.xlsx"

if not path.exists("catalogo_streaming_argentina_2024.xlsx"):
    download(url_streaming)
else:
    print("El archivo del catálogo ya existe.")

# ii) Leer el archivo
import pandas as pd
# A diferencia del CSV, usamos read_excel()
df_streaming = pd.read_excel("catalogo_streaming_argentina_2024.xlsx")

# iii) Imprimir la cabecera
print("Las columnas del catálogo son:")
print(df_streaming.columns.tolist())

# iv) Imprimir los primeros 5 registros
# Imprimimos la cabecera y el vistazo de datos
display(df_streaming.head())

# v) Imprimir el resumen estadístico
# Usamos include='all' para que también nos dé info de las columnas de texto
display(df_streaming.describe(include='all'))

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 567.5 kB/s eta 0:00:00 kB/s eta 0:00:01:01
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
El archivo del catálogo ya existe.
Las columnas del catálogo son:
['title', 'platform', 'type', 'imdbVotes', 'imdbScore', 'tmdbPopularity', 'tmdbScore', 'runtime', 'genres', 'director', 'year_range', 'url']

,title,platform,type,imdbVotes,imdbScore,tmdbPopularity,tmdbScore,runtime,genres,director,year_range,url
0,Cadena perpetua,Max,MOVIE,2906253.0,9.3,159.594,8.705,142,"Drama, Crimen",Frank Darabont,1900_2002,https://play.max.com/movie/9b4dacba-2f80-4272-...
1,El caballero oscuro,Max,MOVIE,2893241.0,9.0,111.674,8.516,152,"Misterio & Suspense, Drama, Acción & Aventura,...",Christopher Nolan,2003_2010,https://play.max.com/movie/52217243-a137-45d6-...
2,Origen,Max,MOVIE,2570263.0,8.8,139.644,8.369,148,"Ciencia ficción, Acción & Aventura, Misterio &...",Christopher Nolan,2003_2010,https://play.max.com/movie/14552c93-d318-4563-...
3,El club de la lucha,Disney Plus,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1998_2004,https://disneyplus.bn5x.net/c/1206980/705874/9...
4,El club de la lucha,Netflix,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1995_2005,http://www.netflix.com/title/26004747

,title,platform,type,imdbVotes,imdbScore,tmdbPopularity,tmdbScore,runtime,genres,director,year_range,url
count,19817,19817,19817,1.785400e+04,17927.000000,19538.000000,18954.000000,19817.000000,19665,14626,19817.0,19817
unique,18008,6,2,NaN,NaN,NaN,NaN,NaN,4189,8812,27.0,19062
top,Perdida,Netflix,MOVIE,NaN,NaN,NaN,NaN,NaN,Documental,Steven Spielberg,2022.0,http://www.netflix.com/title/81665878
freq,5,7109,14060,NaN,NaN,NaN,NaN,NaN,1277,27,1697.0,2
mean,NaN,NaN,NaN,4.838858e+04,6.399520,41.195589,6.461363,80.542867,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,1.488473e+05,1.200258,131.031366,1.254487,37.092943,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,5.000000e+00,1.100000,0.001000,0.500000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,4.620000e+02,5.700000,5.433250,5.889500,48.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2.849500e+03,6.500000,14.428500,6.600000,89.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2.196975e+04,7.300000,33.312500,7.273750,105.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2.906253e+06,9.700000,4173.518000,10.000000,263.000000,NaN,NaN,NaN,NaN

Análisis de los tipos de datos en catalogo_streaming_argentina_2024:

title (Título): Cualitativa nominal. Representa el nombre del contenido.

platform (Plataforma): Cualitativa nominal. Indica dónde está disponible (Netflix, Max, Disney, etc.).

type (Tipo): Cualitativa nominal (binaria). Clasifica la obra en MOVIE o TV SHOW.

imdbVotes (Votos de IMDB): Cuantitativa discreta. Es el conteo de cuánta gente votó en la plataforma IMDB (aunque Pandas a veces le agregue un .0 decimal por defecto).

imdbScore (Puntaje de IMDB): Cuantitativa continua. Promedio de calificación (0.0 a 10.0).

tmdbPopularity (Popularidad TMDB): Cuantitativa continua. Índice matemático de relevancia.

tmdbScore (Puntaje de TMDB): Cuantitativa continua. Promedio de calificación en TMDB.

runtime (Duración): Cuantitativa discreta. Medida en minutos.

genres (Géneros): Cualitativa nominal. Categorías temáticas.

director: Cualitativa nominal. Quien dirigió la obra.

year_range (Rango de años): Cualitativa ordinal. Expresa en qué momento salió el título, a veces agrupando en rangos (ej: 1990_2002), lo cual indica una época.

url: Cualitativa nominal. El enlace directo para reproducir la obra.

Preguntas analíticas propuestas:

¿Cuál es la plataforma dominante (con más títulos) en el mercado argentino actual?

¿Cuál es la obra con mayor duración (runtime) para armar una maratón extrema?

¿Cuál es la mejor película estrictamente del catálogo de Max (según IMDb)?

¿Cuántas obras están catalogadas dentro del género "Documental"?

¿Quién es el director que tiene más obras subidas en Netflix?

In [34]:
# 1. Plataforma con más contenido en Argentina
conteo_plataformas = df_streaming['platform'].value_counts().index[0]
conteo_plataformas_count = df_streaming['platform'].value_counts().iloc[0]
print(f"1) Cantidad de contenido por plataforma:\n{conteo_plataformas} con {conteo_plataformas_count} contenidos\n")

1) Cantidad de contenido por plataforma:
Netflix con 7109 contenidos

In [36]:
# 2. Obra con mayor duración (runtime)
# Ordenamos de mayor a menor (ascending=False) y nos quedamos con el primer registro
obra_mas_larga = df_streaming.sort_values(by='runtime', ascending=False).iloc[0]
print(f"2) La obra más larga es '{obra_mas_larga['title']}' y dura {obra_mas_larga['runtime']} minutos.\n")

2) La obra más larga es 'Lord of the Rings: Return of the King (Extended Edition)' y dura 263 minutos.

In [37]:
# 3. Mejor película en Max
# Filtramos que sea Max Y que sea Película
peliculas_max = df_streaming[(df_streaming['platform'] == 'Max') & (df_streaming['type'] == 'MOVIE')]
mejor_peli_max = peliculas_max.sort_values(by='imdbScore', ascending=False).iloc[0]
print(f"3) La mejor película en Max es '{mejor_peli_max['title']}' con un puntaje de {mejor_peli_max['imdbScore']}.\n")

3) La mejor película en Max es 'Cadena perpetua' con un puntaje de 9.3.

In [38]:
# 4. Cantidad de Documentales
# Usamos el truco ninja del .str.contains() y .fillna('') para evitar errores con vacíos
documentales = df_streaming[df_streaming['genres'].fillna('').str.contains('Documental')]
print(f"4) Hay {len(documentales)} títulos etiquetados como 'Documental' en total.\n")

4) Hay 3031 títulos etiquetados como 'Documental' en total.

In [39]:
# 5. Director estrella en Netflix
# Filtramos solo Netflix, sacamos la columna directores y armamos el conteo
titulos_netflix = df_streaming[df_streaming['platform'] == 'Netflix']
mejor_director = titulos_netflix['director'].value_counts().index[0]
mejor_director_cantidad = titulos_netflix['director'].value_counts().iloc[0]
print(f"5) El director con más títulos en Netflix es {mejor_director} (con {mejor_director_cantidad} obras).")

5) El director con más títulos en Netflix es Raúl Campos, Jan Suter (con 18 obras).